In [2]:
import numpy as np

In [13]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [14]:
type(my_list)

list

In [15]:
type(my_array)

numpy.ndarray

In [16]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Linspace

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

# Arange

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Zeros and Ones

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Eye

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random

#### Numpy has lot of ways to create random number arrays

## Rand

#### Creates an array of the given shape and populates it with random samples from a uniform distributor [0,1)

In [ ]:
np.random.rand(2)#generating 

array([0.12226728, 0.35401019])

In [26]:
np.random.rand(4)

array([0.41539209, 0.02831093, 0.32752354, 0.81951523])

In [28]:
np.random.rand(5,5)

array([[0.33210456, 0.38305565, 0.30422097, 0.85248938, 0.78819572],
       [0.98496434, 0.85278053, 0.04083083, 0.42212085, 0.63741328],
       [0.72656949, 0.13966565, 0.89587603, 0.27936467, 0.45120736],
       [0.46083358, 0.83538715, 0.19959459, 0.24782918, 0.53472478],
       [0.42664522, 0.73340944, 0.82207275, 0.29171084, 0.32054269]])

In [29]:
#it can create 1 dimensional and 2 dimensional arrays

# Randint

#### Returns random integers where the lowest number is inclusive but the highest exclusive

In [34]:
np.random.randint(1,100)

67

In [55]:
np.random.randint(1,100,10)

array([36, 76, 99,  1, 63, 66, 13, 67, 74, 32])

## Seed

In [127]:
np.random.seed(67)
np.random.rand(4)

array([0.54585143, 0.85885661, 0.68589259, 0.33159182])

In [11]:
np.random.seed(11)
np.random.randint(1,100,4)

array([26, 64, 81, 92])

# Array Attributes and Methods

In [99]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# Reshape
#### Returns and array with the same info but a new shape

In [101]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [102]:
arr.reshape(3,8)

ValueError: cannot reshape array of size 25 into shape (3,8)

In [103]:
arr.reshape(3,10)

ValueError: cannot reshape array of size 25 into shape (3,10)

In [121]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [104]:
ranarr

array([19, 23, 39, 28, 14, 23,  8, 25, 46, 42])

In [108]:
ranarr.max()

np.int64(46)

In [109]:
ranarr.argmax()

np.int64(8)

In [110]:
ranarr.min()

np.int64(8)

In [111]:
ranarr.argmin()

np.int64(6)

In [112]:
#arg means which position the called thing is. P.S. the first position starts at 0

# Shape
#### Shape is an attribute arrays have

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [115]:
arr.shape

(25,)

In [116]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [119]:
arr.reshape(1,25).shape

(1, 25)

In [118]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])